
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - hades.kubeforge.io
  resources:
  - configs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - hades.kubeforge.io
  resources:
  - configs/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - hades.kubeforge.io
  resources:
  - projects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - get
  - watch
  - create
  - update
  - patch
- apiGroups:
  - hades.kubeforge.io
  resources:
  - projects
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - hades.kubeforge.io
  resources:
  - projects/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - hades.kubeforge.io
  resources:
  - configs
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - get
  - watch
  - create
  - update
  - patch
